model_args:
  load_model: false  # bool
  load_model_path: saved_models/saved_model.h5  # str
  save_model: true  # bool
  save_model_path: saved_models/saved_model.h5  # str
  learning_rate: 0.0001  # float
  batch_size: 100  # int
  num_epochs: 60  # int
conversion_args:
  quantize: true  # bool
  out_dir: build/  # str
dataset_args:
  raw_dataset_path: /Volumes/LioDrive/Datasets/TinyRadar11G/data  # str
  built_dataset_path: /Volumes/LioDrive/Datasets/TinyRadar11G/built  # str
  num_sessions: 2  # int
  num_instances: 3  # int
  sweep_frequency: 160  # int
  range_points_per_sweep: 492  # int
  stride: 16  # int
  num_windows: 5  # int
  sweeps_per_window: 32  # int
  num_people: 3  # int
  num_single_user_sessions: 0  # int
  gestures:  # list
  - PinchIndex  # list
  - PinchPinky  # list
  - FingerSlider  # list
  - FingerRub  # list
  shuffle: true # bool
  dataset_shuffle_seed: 0  # int
  train_split: 0.8  # float
  val_split: 0.1  # float
  test_split: 0.1  # float
serial_args:
  serial_port: /dev/tty.usbmodem103  # str
  baudrate: 115200  # int
  receive_chunk_size: 7  # int
logging_args:
  name: my_logger  # str
  level: INFO  # str
  log_to_file: true  # bool
  log_dir_path: logs/  # str
  file_mode: a  # str
  log_to_stdout: true  # bool
  format: '%(asctime)s | %(name)s | %(levelname)s: %(message)s'  # str
  datefmt: '%H:%M:%S'  # str
